#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npx is-ci && exit 0
npm run lint:staged
npm test

cd ./docs || exit
npm run spellcheck-docs

cd ../examples/askui-nodejs-base-example || exit
npm run lint:staged
